// <auto-generated />
using System;
using Analytics.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Api.DAL.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Api.DAL.Entities.DailyStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("UN")
                        .HasComment("Код страны");

                    b.Property<string>("OperatingSystem")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Unknown")
                        .HasComment("Операционная система");

                    b.Property<DateTime>("StatDate")
                        .HasColumnType("date")
                        .HasComment("Дата статистики");

                    b.Property<int>("VisitsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Количество посещений");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("idx_dailystats_countrycode");

                    b.HasIndex("StatDate")
                        .IsDescending()
                        .HasDatabaseName("idx_dailystats_statdate");

                    b.HasIndex("StatDate", "CountryCode", "OperatingSystem")
                        .IsUnique()
                        .HasDatabaseName("uq_dailystats_date_country_os")
                        .HasFilter("\"CountryCode\" IS NOT NULL AND \"OperatingSystem\" IS NOT NULL");

                    b.ToTable("DailyStats", null, t =>
                        {
                            t.HasComment("Агрегированная ежедневная статистика");
                        });
                });

            modelBuilder.Entity("Analytics.Api.DAL.Entities.PageVisitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Время посещения в UTC");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_pagevisits_createdat");

                    b.HasIndex("OperatingSystem")
                        .HasDatabaseName("idx_pagevisits_os");

                    b.HasIndex("VisitTime")
                        .IsDescending()
                        .HasDatabaseName("idx_pagevisits_visittime");

                    b.ToTable("PageVisits", null, t =>
                        {
                            t.HasComment("Таблица для хранения посещений страниц");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
